### PR TITLE
heatbath and overrelaxation

### PR DESCRIPTION
**Pull request by simone-romiti**
Current issue: the algorithm seems to not agree with the metropolis for $\beta\approx 1.5$ and $\xi_0=1.0$

### CODE REVIEW

**Comment by simone-romiti** [comment]
@urbach @christianegross 
I solved the problem with the last commit. You can check the agreement between metropolis and heatbath+overrelaxation with the attached input file.

We now sample from the p.d.f. $P(\phi) = e^{\rho \, \cos(\phi)}$ using a metropolis algorithm.

Previous mistake: sampling from the wrong distribution. 
**Note**: we can't use the inverse cumulative function method. The distribution is $P(\phi) = e^{\rho \, \cos(\phi)}$ in $\\phi$ (not in $x=\cos(\phi)$ ). The analytic form of the cumulative density function is not known:  https://math.stackexchange.com/questions/2468863/what-is-the-integral-of-e-cos-x

**Comment by urbach** [comment]
Is it any better than Metropolis?
-- 
C. Urbach
***@***.***

**Comment by simone-romiti** [comment]
Apparently yes. I have attached the input and the uwerr analysis. The first plots are for the metropolis, the others for the heathbath+overrelaxation.
[main.txt](https://github.com/urbach/su2/files/13917219/main.txt)
[Rplots.pdf](https://github.com/urbach/su2/files/13917218/Rplots.pdf)

**Comment by simone-romiti** [comment]
DONE: implementation of Hattori-Nakajima: 
- https://arxiv.org/pdf/hep-lat/9210016v1.pdf
- https://www.sciencedirect.com/science/article/pii/092056329290356W

For $\beta = 1.3$ and $\xi_0=1.0$ the acceptance rate is 0.9 compared to 0.3 of the previous implementation.

**Comment by urbach** [comment]
> DONE: implementation of Hattori-Nakajima: 
> - https://arxiv.org/pdf/hep-lat/9210016v1.pdf
> - https://www.sciencedirect.com/science/article/pii/092056329290356W
> 
> For $\beta = 1.3$ and $\xi_0=1.0$ the acceptance rate is 0.9 compared to 0.3 of the previous implementation.

this sound excellent. All methods agree with eachother?

**Comment by simone-romiti** [comment]
@christianegross we are ready to merge, aren't we?

**Comment by christianegross** [comment]
> @christianegross we are ready to merge, aren't we?

Somehow the restriction of threads to a maximum of T disappeared. I think we should also change the setting of the seeds in the metropolis, so that we do not generate any overlaps if the number of threads is changed.

**Comment by christianegross** [comment]
@simone-romiti Now I cannot think of anything else.

**Comment by simone-romiti** [comment]
Thank you!

**Pull request merged**
