### PR TITLE
Write glueball interpolators and correlators in hadron format

### PR DESCRIPTION
**Pull request by simone-romiti**
I've written a python script in the folder `hadron/`, that converts the data for the interpolators and correlators of the glueball in a format easily readable by the `R` library `hadron`.
A few remarks:

1. This is done in a separate step and not directly in the `C++` code on purpose. One may want to generate configurations and do offline measurements afterwards in parallel (multiple jobs, one for each bunch of measurements).
2. The scripts takes care of deleting the files in the old format. For each choice of the parameters and interpolator type, only 4 files are saved in the corresponding folders:
  - `iconf.dat` : list of trajectory indices that have been put in `hadron` format
  - `pp.dat`, `pm.dat`, `mp.dat`, `mm.dat`: correlators
3. The storage space saved in this way is mostly negligible, but avoids potential filesystem slowdowns due to the access to large number of files. Besides, the analysis scripts won't have to cope with reading the configurations one by one.
4. The script uses the same input file used for the runs
5. The branch is called `h5_format` only for "historical" reasons. I started writing a test program embedding https://github.com/BlueBrain/HighFive in order to produce output in `.h5` format.

To do:

- [ ] write the documentation for this
- [x] `CMakeLists.txt`: make `HighFive` dependency optional

### CODE REVIEW

**Comment by simone-romiti** [comment]
@christianegross when you have some time, could you please test the implementation?

**Comment by kostrzewa** [comment]
f I understood correctly, this helps to convert old correlation functions from many flat text files to different, accumulated, flat text files (`to_csv`), right? If the resulting correlators are indeed stored in csv format, then the filenames should reflect this.

Having said that, this does not resolve the core problem: you will still be performing hundreds of thousands of flat text file operations, but this time at least twice.

I would really again recommend the usage of HDF5 here, although the point about performing measurements in parallel is of course a valid one. The only workaround (unless you want to rely on virtual datasets, see https://docs.h5py.org/en/stable/vds.html ) is to use multiple output files (for instance, by chunking your measurements and reflecting the ranges of measurement IDs in the respective filenames).

Chunked measurements will have the added benefit that they can be processed in parallel, speeding up reading somewhat at the cost of some concatenation to form the final object in the analysis.

**Comment by simone-romiti** [comment]
@kostrzewa yes, you understood correctly, is just a simple and fast workaround for the data that I have available now.
At the moment my `R` analysis scripts reads the files one by one anyhow (causing the script to be slower). With this, I'll do it only once.

You're right when saying my script does not solve the core problem. About HighFive, is it really necessary to use that library? 
My idea is to use this script to prepare the data in the format that I'll use  in the future, and then add to the code the part that generates the `csv` chunks internally instead of multiple text files. This would solve the issue of the large number of files and allows to apply your idea of combining the chunks afterwards.

**Comment by kostrzewa** [comment]
> You're right when saying my script does not solve the core problem. About HighFive, is it really necessary to use that library?

When using HDF5, using HighFive is certainly easier than writing your own HDF5 Writer / Loader using the C API. The one in CVC is over 2000 LOC and does less than I did with some 200 LOC using HighFive.

>  My idea is to use this script to prepare the data in the format that I'll use in the future, and then add to the code the part that generates the csv chunks internally instead of multiple text files. This would solve the issue of the large number of files and allows to apply your idea of combining the chunks afterwards.

Using a text-based format has the drawback that the files require more space than a binary representation, so you should consider this. Beyond that, I agree with you: writing directly to chunked csv files may be a way to go with the data stored in a wide format (such that every line in the file features all the meta-data required to identify the context). Having all the meta-data duplicated in each line of course leads to requiring even more space. Here you should perhaps think into the future a bit and estimate how much space you will need in a year, in two years and so on.

**Comment by simone-romiti** [comment]
plase see the `boundary_conditions` branch

**Pull request closed without merging**
